"""
Sample generator script for Agent 2.
Generates 3 sample outputs and saves them to deliverables/samples/copywriting-ads/
Run with: python generate_samples.py
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Add parent for imports if needed
sys.path.insert(0, str(Path(__file__).parent))

from copywriting_ads_agent import CopywritingAdsAgent

OUTPUT_DIR = Path(__file__).parent.parent / "deliverables" / "samples" / "copywriting-ads"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def banner(title: str):
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print("=" * 60)

def progress(msg: str):
    print(f"  {msg}")

def generate_sample_1_facebook(agent: CopywritingAdsAgent):
    banner("Sample 1 — Facebook Ad")
    params = {
        "product_or_service": "Lumina Ergonomic Chair",
        "target_audience": "Remote workers who sit for 8+ hours a day",
        "campaign_objective": "Direct sales / Conversion",
        "key_benefit": "Actively corrects your posture so you end the day without back pain",
        "pain_point": "Lower back stiffness and shoulder tension at 4 PM",
        "offer": "15% off with code POSTURE",
        "brand_tone": "Empathetic, modern, slightly urgent",
        "generate_image": False # Disabled for sample text file
    }

    result = agent.generate("facebook", params, on_progress=progress)

    content = f"""# Sample 1 — Facebook Ad

## Input / Brief

| Field | Value |
|---|---|
| Product | {params['product_or_service']} |
| Audience | {params['target_audience']} |
| Objective | {params['campaign_objective']} |
| Key Benefit | {params['key_benefit']} |
| Pain Point | {params['pain_point']} |
| Offer | {params['offer']} |
| Tone | {params['brand_tone']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Strategic Analysis
{result['analysis']}

---

## Generated Output
{result['final']}
"""

    out_path = OUTPUT_DIR / "sample-1-facebook-ad.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")


def generate_sample_2_google(agent: CopywritingAdsAgent):
    banner("Sample 2 — Google Ads")
    params = {
        "product_or_service": "Enterprise Cloud Backup",
        "target_keywords": "enterprise cloud backup, ransomware protection, secure data recovery",
        "search_intent": "High-intent IT directors looking for secure, reliable backups after a recent industry ransomware scare.",
        "target_audience": "IT Directors, CIOs",
        "key_benefits": "99.999% uptime, immutable backups, 15-minute recovery time",
        "offer": "Book a Demo"
    }

    result = agent.generate("google", params, on_progress=progress)

    content = f"""# Sample 2 — Google Ads

## Input / Brief

| Field | Value |
|---|---|
| Product | {params['product_or_service']} |
| Keywords | {params['target_keywords']} |
| Intent | {params['search_intent']} |
| Audience | {params['target_audience']} |
| Benefits | {params['key_benefits']} |
| Offer/CTA | {params['offer']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Strategic Analysis
{result['analysis']}

---

## Generated Output
{result['final']}
"""

    out_path = OUTPUT_DIR / "sample-2-google-ads.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")


def generate_sample_3_email(agent: CopywritingAdsAgent):
    banner("Sample 3 — Email Copy")
    params = {
        "objective": "Product Launch Announcement",
        "product_or_service": "Zenith Noise-Cancelling Earbuds",
        "target_audience": "Existing customers who bought the previous generation",
        "offer": "Early access 24 hours before the public + free shipping",
        "brand_tone": "Excited, exclusive, premium"
    }

    result = agent.generate("email", params, on_progress=progress)

    content = f"""# Sample 3 — Email Copy

## Input / Brief

| Field | Value |
|---|---|
| Objective | {params['objective']} |
| Product | {params['product_or_service']} |
| Audience | {params['target_audience']} |
| Offer | {params['offer']} |
| Tone | {params['brand_tone']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Strategic Analysis
{result['analysis']}

---

## Generated Output
{result['final']}
"""

    out_path = OUTPUT_DIR / "sample-3-email-copy.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")


if __name__ == "__main__":
    print("Copywriting & Ads Agent — Sample Generator")
    try:
        agent = CopywritingAdsAgent()
        info = agent.get_provider_info()
        print(f"\n✓ Connected: {info['provider']} / {info['model']}")
    except EnvironmentError as e:
        print(f"\n✗ {e}")
        sys.exit(1)

    try:
        generate_sample_1_facebook(agent)
        generate_sample_2_google(agent)
        generate_sample_3_email(agent)
    except RuntimeError as e:
        print(f"\n✗ Generation error: {e}")
        sys.exit(1)

    print(f"\n{'=' * 60}")
    print("  All 3 samples generated successfully!")
    print(f"  Saved to: deliverables/samples/copywriting-ads/")
    print("=" * 60)
