"""
Sample generator script.
Generates all three sample outputs and saves them to deliverables/samples/content-writing/
Run with: python generate_samples.py
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Add parent for imports if needed
sys.path.insert(0, str(Path(__file__).parent))

from content_writing_agent import ContentWritingAgent

OUTPUT_DIR = Path(__file__).parent.parent / "deliverables" / "samples" / "content-writing"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def banner(title: str):
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print("=" * 60)


def progress(msg: str):
    print(f"  {msg}")


def generate_sample_1_blog(agent: ContentWritingAgent):
    banner("Sample 1 — Blog Post")
    params = {
        "topic": "The hidden cost of poor sleep on workplace performance",
        "audience": "Working professionals and managers",
        "tone": "Authoritative yet accessible",
        "purpose": "Educate readers on the productivity impact of sleep deprivation and inspire better sleep habits",
        "desired_length": "1000–1500 words",
        "additional_instructions": "Include practical, actionable tips in the latter half of the post.",
    }

    result = agent.generate("blog", params, on_progress=progress)

    content = f"""# Sample 1 — Blog Post

## Input / Brief

| Field | Value |
|---|---|
| Topic | {params['topic']} |
| Target Audience | {params['audience']} |
| Tone | {params['tone']} |
| Purpose | {params['purpose']} |
| Desired Length | {params['desired_length']} |
| Additional | {params['additional_instructions']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Generated Output

{result['final']}
"""

    out_path = OUTPUT_DIR / "sample-1-blog.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")
    return result


def generate_sample_2_website(agent: ContentWritingAgent):
    banner("Sample 2 — Website Content")
    params = {
        "page_type": "Homepage",
        "business_name": "FlowStack",
        "product_or_service": "An AI-powered project management platform for remote software teams",
        "target_audience": "Engineering managers and CTO-level leaders at growing tech startups (20–200 employees)",
        "value_proposition": "FlowStack reduces sprint planning time by 60% and surfaces blockers before they delay delivery — without adding meetings or process overhead",
        "tone": "Confident and direct, with a modern tech brand feel",
        "conversion_goal": "Start a free 14-day trial",
        "additional_instructions": "Emphasise the async-first angle. The audience has remote teams across time zones.",
    }

    result = agent.generate("website", params, on_progress=progress)

    content = f"""# Sample 2 — Website Content (Homepage)

## Input / Brief

| Field | Value |
|---|---|
| Page Type | {params['page_type']} |
| Business | {params['business_name']} |
| Product | {params['product_or_service']} |
| Target Audience | {params['target_audience']} |
| Value Proposition | {params['value_proposition']} |
| Tone | {params['tone']} |
| Conversion Goal | {params['conversion_goal']} |
| Additional | {params['additional_instructions']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Generated Output

{result['final']}
"""

    out_path = OUTPUT_DIR / "sample-2-website-content.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")
    return result


def generate_sample_3_seo(agent: ContentWritingAgent):
    banner("Sample 3 — SEO Article")
    params = {
        "topic": "How to build a morning routine that genuinely improves productivity",
        "primary_keyword": "morning routine for productivity",
        "secondary_keywords": "morning habits, productive morning, daily routine tips, how to wake up early, morning schedule",
        "target_audience": "Working professionals aged 25–40 looking to improve their output without burning out",
        "search_intent": "Informational",
        "desired_length": "1200–1800 words",
        "additional_instructions": "Include a practical step-by-step routine in the body. Avoid generic advice like 'drink water'.",
    }

    result = agent.generate("seo", params, on_progress=progress)

    content = f"""# Sample 3 — SEO Article

## Input / Brief

| Field | Value |
|---|---|
| Topic | {params['topic']} |
| Primary Keyword | {params['primary_keyword']} |
| Secondary Keywords | {params['secondary_keywords']} |
| Target Audience | {params['target_audience']} |
| Search Intent | {params['search_intent']} |
| Desired Length | {params['desired_length']} |
| Additional | {params['additional_instructions']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Generated Output

{result['final']}
"""

    out_path = OUTPUT_DIR / "sample-3-seo-article.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")
    return result


if __name__ == "__main__":
    print("Content Writing Agent — Sample Generator")
    print("Generating 3 samples using the live Gemini API...")

    try:
        agent = ContentWritingAgent()
        info = agent.get_provider_info()
        print(f"\n✓ Connected: {info['provider']} / {info['model']}")
    except EnvironmentError as e:
        print(f"\n✗ {e}")
        sys.exit(1)

    try:
        generate_sample_1_blog(agent)
        generate_sample_2_website(agent)
        generate_sample_3_seo(agent)
    except RuntimeError as e:
        print(f"\n✗ Generation error: {e}")
        sys.exit(1)

    print(f"\n{'=' * 60}")
    print("  All 3 samples generated successfully!")
    print(f"  Saved to: deliverables/samples/content-writing/")
    print("=" * 60)
