"""
Sample generator script for Agent 3.
Generates 3 sample outputs and saves them to deliverables/samples/video-production/
Run with: python generate_samples.py

Requires a working GEMINI_API_KEY in .env with network access to Google's
Generative Language API.
"""

import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).parent))

from video_production_agent import VideoProductionAgent

OUTPUT_DIR = Path(__file__).parent.parent / "deliverables" / "samples" / "video-production"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def banner(title: str):
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print("=" * 60)


def progress(msg: str):
    print(f"  {msg}")


def generate_sample_1_video_script(agent: VideoProductionAgent):
    banner("Sample 1 — Video Script")
    params = {
        "topic": "How Lumina Ergonomic Chair fixes 4pm back pain for remote workers",
        "objective": "Drive traffic to the product page and build desire before the offer",
        "audience": "Remote workers in their late 20s-40s who sit for 8+ hours a day",
        "platform": "YouTube (long-form)",
        "duration": "45 seconds",
        "tone": "Empathetic, modern",
        "style": "Documentary-style with quick product cutaways",
        "key_message": "Your chair is quietly breaking your body down — Lumina fixes that",
        "cta": "Shop Lumina today and take 15% off with code POSTURE",
        "additional_instructions": "Open on the specific 4pm slump moment rather than the product.",
    }
    result = agent.generate("video_script", params, on_progress=progress)
    content = f"""# Sample 1 — Video Script

## Input / Brief

| Field | Value |
|---|---|
| Topic | {params['topic']} |
| Objective | {params['objective']} |
| Audience | {params['audience']} |
| Platform | {params['platform']} |
| Duration | {params['duration']} |
| Tone | {params['tone']} |
| Style | {params['style']} |
| Key Message | {params['key_message']} |
| CTA | {params['cta']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Scene Plan
{result['plan']}

---

## Generated Output
{result['final']}

---

{result['timing_report']}
"""
    out_path = OUTPUT_DIR / "sample-1-video-script.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")


def generate_sample_2_storyboard(agent: VideoProductionAgent):
    banner("Sample 2 — Storyboard")
    params = {
        "concept_or_script": (
            "A 20-second product video for the Lumina Ergonomic Chair. Opens on a remote "
            "worker slumping at 4pm, visibly uncomfortable. Cuts to the chair's adaptive "
            "lumbar support in close-up. Ends on the same worker now upright and relaxed, "
            "with the Lumina logo and a 15% off code."
        ),
        "platform": "Instagram Reels",
        "duration": "20 seconds",
        "tone": "Warm, aspirational",
        "style": "Natural light, shallow depth of field, no overly polished stock-photo feel",
        "generate_reference_image": False,
    }
    result = agent.generate("storyboard", params, on_progress=progress)
    content = f"""# Sample 2 — Storyboard

## Input / Brief

| Field | Value |
|---|---|
| Concept | {params['concept_or_script']} |
| Platform | {params['platform']} |
| Duration | {params['duration']} |
| Tone | {params['tone']} |
| Style | {params['style']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Visual Language Plan
{result['visual_plan']}

---

## Generated Output
{result['final']}

---

{result['timing_report']}
"""
    out_path = OUTPUT_DIR / "sample-2-storyboard.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")


def generate_sample_3_social_video(agent: VideoProductionAgent):
    banner("Sample 3 — Social Media Video")
    params = {
        "topic": "The one adjustment most people get wrong on their office chair",
        "platform": "TikTok",
        "audience": "Remote workers and desk workers scrolling TikTok on a break",
        "duration": "15 seconds",
        "tone": "Energetic, a little cheeky",
        "key_message": "Lumbar height, not seat height, is the adjustment nobody makes",
        "cta": "Follow for more desk setup fixes",
    }
    result = agent.generate("social_video", params, on_progress=progress)
    content = f"""# Sample 3 — Social Media Video

## Input / Brief

| Field | Value |
|---|---|
| Topic | {params['topic']} |
| Platform | {params['platform']} |
| Audience | {params['audience']} |
| Duration | {params['duration']} |
| Tone | {params['tone']} |
| Key Message | {params['key_message']} |
| CTA | {params['cta']} |

**Generated by:** {result['provider']} · Model: `{result['model']}`

---

## Hook & Retention Plan
{result['hook_plan']}

---

## Generated Output
{result['final']}

---

{result['timing_report']}
"""
    out_path = OUTPUT_DIR / "sample-3-social-video.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"\n  ✓ Saved: {out_path}")


if __name__ == "__main__":
    print("Video Production Agent — Sample Generator")
    try:
        agent = VideoProductionAgent()
        info = agent.get_provider_info()
        print(f"\n✓ Connected: {info['provider']} / {info['model']}")
    except EnvironmentError as e:
        print(f"\n✗ {e}")
        sys.exit(1)

    try:
        generate_sample_1_video_script(agent)
        generate_sample_2_storyboard(agent)
        generate_sample_3_social_video(agent)
    except RuntimeError as e:
        print(f"\n✗ Generation error: {e}")
        sys.exit(1)

    print(f"\n{'=' * 60}")
    print("  All 3 samples generated successfully!")
    print(f"  Saved to: deliverables/samples/video-production/")
    print("=" * 60)
